#### importing basic libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Getting the dataset

In [2]:
dataset = pd.read_csv('practice.csv')

#### Cropping dataset for meaningful values

In [3]:
dataset = dataset.iloc[:,2:36].values

#### Visualizing the data

In [4]:
dataset = pd.DataFrame(dataset)
dataset

0      1  2       3             4         5          6   \
0         Sherghati  60-65  M  824211  16-18 Months   Prepaid     51-100   
1              Puri  30-35  F  752015  16-18 Months  Postpaid    151-200   
2     Chandrapur Ho  40-45  F  442401    6-8 Months  Postpaid       1-50   
3         Chittapur  35-40  M  585211    0-2 Months   Prepaid    101-150   
4           Majauli  40-45  M  486666  10-12 Months   Prepaid    151-200   
...             ...    ... ..     ...           ...       ...        ...   
9995        Mauganj  25-30  F  486340  12-14 Months   Prepaid    151-200   
9996      Bageshwar  65-70  M  263642   8-10 Months   Prepaid   751-1000   
9997           Muri  60-65  M  791122    4-6 Months   Prepaid       1-50   
9998         Dapoli  45-50  F  415214  10-12 Months   Prepaid     51-100   
9999         Ambala  55-60  F  135003  14-16 Months   Prepaid  1001-1500   

              7         8        9   ... 24               25   26   27  \
0      0GB-0.5GB   301-500     1-50  ...  3  Payment Banking   No   No   
1      0.5GB-1GB   151-200  250-300  ...  4           Wallet  Yes  Yes   
2      1GB-1.5GB   301-500     1-50  ...  1           Wallet   No   No   
3      0GB-0.5GB  751-1000  151-200  ...  4           Wallet  Yes   No   
4     7.5GB-10GB   250-300  501-750  ...  0           Wallet   No  Yes   
...          ...       ...      ...  ... ..              ...  ...  ...   
9995       >15GB   501-750  301-500  ...  5  Payment Banking   No  Yes   
9996   5GB-7.5GB   201-250    >1000  ...  8  Payment Banking   No   No   
9997   2.5GB-5GB   101-150  501-750  ...  1           Wallet  Yes   No   
9998   0.5GB-1GB   301-500  301-500  ...  5  Payment Banking  Yes   No   
9999   5GB-7.5GB   301-500  151-200  ...  6  Payment Banking  Yes   No   

           28        29       30     31   32        33  
0       Shows   Romance  English   2000  Yes  Vodafone  
1       Shows   Romance    Hindi    500   No      Idea  
2     Live TV    Action  English  10000   No      Idea  
3     Live TV    Sci-fi  English   3000  Yes      Idea  
4       Shows    Action    Hindi   2500  Yes      Idea  
...       ...       ...      ...    ...  ...       ...  
9995    Shows   Fantasy    Hindi   5000   No  Vodafone  
9996   Movies    Action    Hindi    500  Yes  Vodafone  
9997   Movies  Thriller    Hindi   2500  Yes  Vodafone  
9998  Live TV  Thriller    Hindi  10000   No  Vodafone  
9999  Live TV   Fantasy    Hindi   7000  Yes      Idea  

[10000 rows x 34 columns]

#### Masking columns of dataset to apply Encoder to Categorical data

In [5]:
categorical_feature_mask = dataset.dtypes==object
categorical_cols = dataset.columns[categorical_feature_mask].tolist()

#### Handling categorical data using LabelEncoder

In [6]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
dataset[categorical_cols] = dataset[categorical_cols].apply(lambda col: label.fit_transform(col))
dataset

0   1   2     3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
0     3121   8   1  6625   4   1   9   1   5   0  ...   3   0   0   0   2   5   
1     2751   2   0  5767   4   0   4   0   2   4  ...   4   1   1   1   2   5   
2      700   4   0  2694  10   0   0   4   5   0  ...   1   1   0   0   0   0   
3      787   3   1  4339   0   1   2   1   8   2  ...   4   1   1   0   0   6   
4     2043   4   1  3096   1   1   4   8   4   6  ...   0   1   0   1   2   0   
...    ...  ..  ..   ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
9995  2142   1   0  3088   2   1   4   9   6   5  ...   5   0   0   1   2   3   
9996   218   9   1  1174  11   1  10   7   3   9  ...   8   0   0   0   1   0   
9997  2280   8   1  6305   9   1   0   5   1   6  ...   1   1   1   0   1   7   
9998   846   5   0  2366   1   1   9   0   5   5  ...   5   0   1   0   0   7   
9999    81   7   0   124   3   1   1   7   5   2  ...   6   0   1   0   0   3   

      30  31  32  33  
0      0   3   1   1  
1      1   0   0   0  
2      0  12   0   0  
3      0   5   1   0  
4      1   4   1   0  
...   ..  ..  ..  ..  
9995   1   7   0   1  
9996   1   0   1   1  
9997   1   4   1   1  
9998   1  12   0   1  
9999   1   9   1   0  

[10000 rows x 34 columns]

#### Making dependent and independent variables

In [7]:
X = dataset.iloc[:, dataset.columns != 14].values
y = dataset.iloc[:,14].values

#### Making training and test data

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1,random_state=0)

#### Scaling data using StandardScaler

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Classification of data using RandomForest Classification

In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

#### Predicting test values

In [11]:
y_pred = classifier.predict(X_test)

#### Comparing Original y_test with y_pred

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [13]:
y_pred

array([1, 0, 4, 2, 4, 3, 1, 4, 3, 2, 6, 2, 4, 3, 2, 0, 1, 6, 4, 5, 6, 6,
       7, 6, 7, 4, 3, 2, 1, 0, 4, 1, 0, 1, 2, 7, 2, 1, 6, 2, 5, 5, 4, 3,
       1, 0, 4, 6, 0, 2, 6, 3, 4, 0, 6, 1, 3, 2, 1, 3, 2, 4, 5, 1, 0, 5,
       3, 0, 2, 7, 3, 1, 1, 7, 7, 5, 3, 1, 7, 4, 2, 4, 6, 2, 2, 6, 0, 0,
       2, 5, 4, 1, 1, 1, 2, 2, 7, 3, 1, 2, 2, 2, 6, 2, 1, 2, 7, 0, 3, 7,
       2, 2, 3, 2, 5, 0, 1, 0, 2, 2, 5, 7, 6, 3, 7, 6, 4, 0, 7, 1, 1, 0,
       0, 0, 4, 0, 0, 3, 5, 4, 6, 3, 0, 6, 6, 6, 7, 7, 0, 3, 0, 5, 0, 3,
       4, 0, 1, 6, 7, 2, 4, 3, 2, 2, 1, 0, 7, 1, 0, 4, 3, 4, 2, 5, 1, 3,
       4, 1, 6, 0, 4, 0, 1, 2, 6, 3, 0, 7, 1, 1, 1, 6, 2, 2, 0, 2, 3, 2,
       6, 4, 0, 0, 5, 7, 1, 1, 2, 4, 3, 7, 1, 3, 2, 0, 7, 1, 3, 0, 3, 5,
       2, 1, 1, 0, 1, 2, 1, 0, 4, 1, 0, 3, 5, 1, 3, 1, 2, 1, 2, 5, 0, 2,
       4, 1, 0, 1, 7, 4, 3, 0, 1, 1, 1, 7, 2, 6, 2, 0, 5, 7, 4, 0, 4, 2,
       2, 0, 3, 1, 5, 7, 6, 5, 7, 7, 3, 5, 3, 4, 6, 0, 0, 3, 7, 4, 7, 0,
       5, 5, 1, 4, 6, 4, 4, 0, 0, 5, 1, 6, 4, 4, 3,

In [14]:
y_test

array([6, 2, 6, 0, 0, 5, 0, 5, 1, 6, 5, 2, 3, 7, 3, 4, 1, 4, 6, 3, 2, 5,
       6, 5, 0, 2, 0, 3, 6, 4, 0, 6, 3, 0, 1, 5, 5, 6, 0, 5, 7, 5, 4, 1,
       7, 1, 6, 3, 7, 5, 2, 5, 0, 3, 2, 6, 5, 1, 1, 6, 6, 5, 1, 7, 5, 3,
       7, 5, 1, 4, 0, 6, 3, 2, 0, 6, 6, 5, 7, 2, 3, 7, 5, 7, 7, 3, 4, 2,
       1, 7, 5, 3, 5, 1, 1, 5, 2, 6, 2, 2, 0, 7, 5, 6, 3, 7, 3, 3, 6, 5,
       3, 2, 6, 0, 6, 5, 0, 5, 5, 4, 4, 1, 0, 7, 2, 1, 5, 0, 7, 5, 2, 3,
       1, 0, 4, 3, 3, 7, 1, 5, 5, 6, 3, 4, 5, 5, 2, 1, 5, 3, 3, 7, 6, 1,
       0, 0, 5, 5, 5, 5, 1, 5, 1, 1, 7, 2, 3, 4, 6, 5, 7, 6, 5, 7, 3, 2,
       4, 6, 4, 6, 4, 4, 1, 6, 1, 5, 1, 6, 2, 0, 7, 4, 7, 1, 7, 5, 7, 2,
       0, 5, 4, 2, 1, 1, 4, 1, 5, 6, 0, 1, 0, 3, 7, 7, 7, 5, 0, 6, 3, 3,
       5, 7, 3, 0, 4, 3, 7, 6, 7, 5, 3, 0, 3, 2, 7, 5, 4, 3, 2, 6, 1, 1,
       3, 7, 0, 3, 2, 5, 0, 3, 0, 6, 0, 5, 4, 7, 1, 1, 5, 5, 0, 2, 6, 2,
       1, 2, 3, 2, 7, 4, 2, 1, 2, 2, 0, 1, 6, 7, 7, 7, 0, 4, 4, 1, 5, 0,
       4, 0, 0, 1, 2, 1, 0, 7, 5, 5, 4, 7, 7, 3, 7,

#### Predicting Accuracy

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.114

In [16]:
cm

array([[18, 26, 13, 18, 13, 14,  4, 12],
       [19, 22, 32, 16,  9, 14, 10, 17],
       [23, 25, 21, 13,  8, 13, 12, 15],
       [21, 30, 21, 15, 11, 12,  8,  9],
       [24, 21, 14, 14, 10,  7, 13, 10],
       [21, 18, 30, 25, 13,  6, 13, 14],
       [19, 29, 10, 20, 16,  9,  7,  9],
       [14, 20, 18, 16, 12, 12,  7, 15]], dtype=int64)